### ISSUE TITLE
Duplicate message when using WithField

### ISSUE THREAD

**Issue by bradleyfalzon** [evalphobia/logrus_stackdriver#2]
Hi,

Given the following program:

```go
package main

import (
        "log"
        "time"

        "github.com/evalphobia/logrus_stackdriver"
        "github.com/sirupsen/logrus"
)

func main() {
        logger := logrus.New()

        hook, err := logrus_stackdriver.New("gopherci-dev", "name")
        if err != nil {
                log.Fatal(err)
        }
        logger.Hooks.Add(hook)

        logger.Infof("this is a test message at %v", time.Now())

        logger2 := logger.WithField("k", "v")

        logger2.Infof("THIS IS A TEST MESSAGE AT %v", time.Now())
}
```

This outputs to console correctly:

```
INFO[0000] this is a test message at 2017-08-23 08:59:31.272113039 +0930 ACST m=+0.000949892  message="this is a test message at 2017-08-23 08:59:31.272113039 +0930 ACST m=+0.000949892"
INFO[0001] THIS IS A TEST MESSAGE AT 2017-08-23 08:59:32.507844295 +0930 ACST m=+1.236681144  k=v message="this is a test message at 2017-08-23 08:59:31.272113039 +0930 ACST m=+0.000949892"
```

But the logs in stackdriver show:

```yaml
[bradleyf@srv4 logrus-stackdriver]$ gcloud --project=gopherci-dev beta logging read --freshness=30s
---
insertId: a03ju1g4ndwstg
jsonPayload:
  k: v
  message: this is a test message at 2017-08-23 08:59:31.272113039 +0930 ACST m=+0.000949892
logName: projects/gopherci-dev/logs/name
receiveTimestamp: '2017-08-22T23:29:33.002297338Z'
resource:
  labels:
    project_id: gopherci-dev
  type: global
severity: INFO
timestamp: '2017-08-22T23:29:33.002297338Z'
---
insertId: pjgy95g4js7gzb
jsonPayload:
  message: this is a test message at 2017-08-23 08:59:31.272113039 +0930 ACST m=+0.000949892
logName: projects/gopherci-dev/logs/name
receiveTimestamp: '2017-08-22T23:29:32.336697476Z'
resource:
  labels:
    project_id: gopherci-dev
  type: global
severity: INFO
timestamp: '2017-08-22T23:29:32.336697476Z'
```

Notice how the message has been duplicated in the `jsonPayload`, but the additional field appears correctly?

**Comment by bradleyfalzon** [comment]
I think the issue may be because of the special handling of the `message` field.

https://github.com/evalphobia/logrus_stackdriver/blob/3ef27bcaba13d1d31acd991aec40d705e805c5a4/data.go#L24-L35

This adds the `message` key to the map in `entry *logrus.Entry` if it's not set already. This is modifying the `*logrus.Entry`, which appears to be reused by logrus for future messages.

You can see this by modifying:

```diff
@@ -84,6 +84,8 @@

 // Fire is invoked by logrus and sends log to kinesis.
 func (h *StackdriverHook) Fire(entry *logrus.Entry) error {
+       log.Print(entry.Message)
+       log.Print(entry.Data["message"])
        if !h.async {
                return h.fire(entry)
        }
```

This then prints:

```
2017/08/23 09:16:38 this is a test message at 2017-08-23 09:16:38.601108955 +0930 ACST m=+0.001410736
2017/08/23 09:16:38 <nil>
INFO[0000] this is a test message at 2017-08-23 09:16:38.601108955 +0930 ACST m=+0.001410736  message="this is a test message at 2017-08-23 09:16:38.601108955 +0930 ACST m=+0.001410736"
2017/08/23 09:16:39 THIS IS A TEST MESSAGE AT 2017-08-23 09:16:39.832593907 +0930 ACST m=+1.232895695
2017/08/23 09:16:39 this is a test message at 2017-08-23 09:16:38.601108955 +0930 ACST m=+0.001410736
INFO[0001] THIS IS A TEST MESSAGE AT 2017-08-23 09:16:39.832593907 +0930 ACST m=+1.232895695  k=v message="this is a test message at 2017-08-23 09:16:38.601108955 +0930 ACST m=+0.001410736"
```

Noting that the first message `entry.Data["message"]` is nil, then, because it's nil `newDataField` sets `entry.Data["message"]` to `entry.Message`. When another message is received, the `entry.Data` map appears to be reused, so `entry.Data["message"]` the first entry's message and the if statement in `newDataField` doesn't overwrite it.

**Comment by bradleyfalzon** [comment]
If this is the case, then I think copying the map before modifying it may be the best idea.

```diff
@@ -22,13 +22,18 @@
 }

 func newDataField(logName string, entry *logrus.Entry) *dataField {
-       if _, ok := entry.Data[fieldMessage]; !ok {
-               entry.Data[fieldMessage] = entry.Message
+       var fields = make(logrus.Fields)
+       for k, v := range entry.Data {
+               fields[k] = v
+       }
+
+       if _, ok := fields[fieldMessage]; !ok {
+               fields[fieldMessage] = entry.Message
        }

        return &dataField{
                defaultLogName: logName,
-               data:           entry.Data,
+               data:           fields,
                logLevel:       entry.Level,
                omitList:       make(map[string]struct{}),
        }
```

This appears to resolve my issue, and also removes the redundant `message=` in the logrus console output:

```
2017/08/23 09:31:32 this is a test message at 2017-08-23 09:31:32.615851689 +0930 ACST m=+0.000954166
2017/08/23 09:31:32 <nil>
INFO[0000] this is a test message at 2017-08-23 09:31:32.615851689 +0930 ACST m=+0.000954166
2017/08/23 09:31:33 THIS IS A TEST MESSAGE AT 2017-08-23 09:31:33.927268113 +0930 ACST m=+1.312370541
2017/08/23 09:31:33 <nil>
INFO[0001] THIS IS A TEST MESSAGE AT 2017-08-23 09:31:33.927268113 +0930 ACST m=+1.312370541  k=v
```

```yaml
[bradleyf@srv4 logrus-stackdriver]$ gcloud --project=gopherci-dev beta logging read --freshness=30s
---
insertId: 1d4cioag4nz17k0
jsonPayload:
  k: v
  message: THIS IS A TEST MESSAGE AT 2017-08-23 09:31:33.927268113 +0930 ACST m=+1.312370541
logName: projects/gopherci-dev/logs/name
receiveTimestamp: '2017-08-23T00:01:34.407990452Z'
resource:
  labels:
    project_id: gopherci-dev
  type: global
severity: INFO
timestamp: '2017-08-23T00:01:34.407990452Z'
---
insertId: 1hk7ilig4nwlgo1
jsonPayload:
  message: this is a test message at 2017-08-23 09:31:32.615851689 +0930 ACST m=+0.000954166
logName: projects/gopherci-dev/logs/name
receiveTimestamp: '2017-08-23T00:01:33.751435329Z'
resource:
  labels:
    project_id: gopherci-dev
  type: global
severity: INFO
timestamp: '2017-08-23T00:01:33.751435329Z'
```

But I'm unsure whether this is even the best way to resolve it, or whether there's another underlying issue.
